version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: always
    volumes:
      - './postgres:/var/lib/postgresql/data'

  postgres_test:
    image: postgres:latest
    container_name: postgres_test
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    ports:
      - 5433:5432
    restart: always

volumes:
  postgres:
