version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DEV_DB}
    ports:
      - ${POSTGRES_DEV_PORT}:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DEV_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - './postgres:/var/lib/postgresql/data'

  postgres_test:
    image: postgres:latest
    container_name: postgres_test
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - ${POSTGRES_TEST_PORT}:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_TEST_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres: